# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jsaldana <jsaldana@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/07/16 20:05:55 by jsaldana          #+#    #+#              #
#    Updated: 2022/07/16 20:06:47 by jsaldana         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = rush-02
SRC = main.c
all: $(NAME)
$(NAME):
	gcc -Wall -Werror -Wextra -o $(NAME) $(SRC)
fclean:
	rm -f $(NAME)
re: fclean all
